name: Run Checks

on: pull_request

permissions:
  id-token: write
  pull-requests: write
  contents: read

jobs:
  broken-links:
    name: Broken Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 8.6.2
      - run: pnpm i --frozen-lockfile
      - run: pnpm run check:links
  vale:
    name: Writing Checks
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 8.6.2
      - run: pnpm install -g mdx2vast
      - uses: errata-ai/vale-action@v2.1.1
        with:
          filter_mode: added
          reporter: github-pr-review
          vale_flags: --minAlertLevel=error
          fail_on_error: false
          token: ${{secrets.GITHUB_TOKEN}}
  integrations:
    name: Integration Versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 8.6.2
      - run: pnpm i --no-frozen-lockfile
      - run: |
          cd .github/scripts
          npm install
      - run: node .github/scripts/checks/check-integrations.js
        env:
          BOTPRESS_TOKEN: ${{ secrets.BOTPRESS_TOKEN }}
          BOTPRESS_WORKSPACE_ID: ${{ secrets.BOTPRESS_WORKSPACE_ID }}